### PR TITLE
fix: Coverage button not visible

### LINKED ISSUE #37: "Coverage: X%" button doesn't appear by default
Testing Item: https://sourcegraph-team.monday.com/boards/322741303/pulses/322741437

Local Sourcegraph started through: `IMAGE=sourcegraph/server:3.8.0-rc.2 ./dev/run-server-image.sh`

While testing for release 3.8, even with setting `"codecov.hideCoverageButton": false,` explicitly defined, I could not see the "Coverage: X%" button on Sourcegraph (local) or GitHub (with extension), but coverage line highlights are visible.

Screenshot from 2019-09-18 12-39-17

On Sourcegraph, after loading a code page with the coverage line highlights, when I navigate to another page then return to the code, by hitting the browser back button, the button appears. So it seems to only render when the page is re-rendered after navigating away and back (maybe component update issue?). After refreshing the page the highlights appear but the button doesn't.

Screenshot from 2019-09-18 12-50-02

### PR DESCRIPTION
**Pull request by hadrian-git**
- fixes #37
- update interface ResolvedURI to reflect resolveURI not throwing on `!path` (#34)

### CODE REVIEW

File: src/uri.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { Endpoint, Settings } from './settings'
 export interface ResolvedURI {
     repo: string
     rev: string
-    path: string
+    path?: string
```
Comment (felixfbecker) [inline src/uri.ts]: Could you document here under which condition this would be `undefined`? The docblock above says the interface identifies a file path, so intuitively not including a `path` does not make sense to me

Comment (lguychard) [reply src/uri.ts]: @felixfbecker context:
- In https://github.com/codecov/sourcegraph-codecov/pull/34/files#diff-8a415beef63a505bd17d360a4c9dce13 I changed `resolveURI()` so that the implementation would match the returned type.
- Turns out `resolveURI` can be called on a root URI, not just a file URI, in which case the URI does not contain a path.

Maybe for clarity & optimal type safety we should separate `resolveRootURI` and `resolveFilURI`:


```typescript
interface ResolvedRootURI {
    repo: string
    rev: string
}

function resolveRootURI(uri: string): ResolvedRootURI {}

interface ResolvedFileURI extends ResolvedRootURI {
    path: string
}

function resolveFileURI(uri: string): ResolvedFileURI {}
```

Thoughts @felixfbecker @hadrian-git ?

Comment (hadrian-git) [reply src/uri.ts]:
```ts
/**
 * A resolved URI without an identified path.
 */
export interface ResolvedRootURI {
    repo: string
    rev: string
}

/**
 * A resolved URI with an identified path.
 */
export interface ResolvedFileURI extends ResolvedRootURI {
    path: string
}

/**
 * Resolve a URI of the form git://github.com/owner/repo?rev#path and file:///path to an absolute reference
 */
export function resolveFileURI(uri: string): ResolvedFileURI {
    // ...
    return {
        repo,
        rev,
        path,
    }
}

/**
 * Resolve a URI of the form git://github.com/owner/repo?rev to an absolute reference
 */
export function resolveRootURI(uri: string): ResolvedRootURI {
    const { path, ...result } = resolveFileUri(uri)
    return result
}
```
wdyt?

Also, can files still have a URI of form `file:///...`? I saw in the test file `uri.test.ts` that `file` is set as an unsupported scheme. Should I update the tests, docs, e.t.c?

Comment (felixfbecker) [reply src/uri.ts]: I would prefer two functions as one of them can throw an Error. But the most important part is proper documentation (which caused this bug in the first place)

**Comment by felixfbecker** [comment]
FYI @hadrian-git your git email or GitHub profile are not configured to match each other :)

File: src/uri.ts (hunk 1 above)
Comment (hadrian-git) [reply src/uri.ts]: yep, can also be

```ts
function resolveURI(url: URL): ResolvedRootURI {
    // ...
    return { repo, rev }
}

export function resolveFileURI(uri: string): ResolvedFileURI {
    const url = new URL(uri)
    const path = url.hash.slice(1)
    return {
        ...resolveURI(url),
        path,
    }
}

export function resolveRootURI(uri: string): ResolvedRootURI {
    return resolveURI(new URL(uri))
}
```

**Comment by hadrian-git** [comment]
> FYI @hadrian-git your git email or GitHub profile are not configured to match each other :)
Will that cause problems?

I have a separate user for "work only" that has git configured up with my Sourcegraph email, and the other user for "personal stuff" with my GitHub email...

note: I updated my user.name now to full name

**Comment by felixfbecker** [comment]
It just means it won't be possible to easily link from your commits to your profile or identify your commits by your avatar on PR pages.

You can add your Sourcegraph email as a secondary email to GitHub to make it consider that as "your" email too

File: src/uri.ts [hunk 2]
```diff
@@ -24,15 +29,16 @@ export function resolveURI(uri: string): ResolvedURI {
...
-    if (!path) {
-        throw new Error('Could not determine file path')
-    }
+    return { repo, rev }
+}
+
+/**
+ * Resolve a URI of the forms git://github.com/owner/repo?rev#path and file:///path to an absolute reference
+ */
+export function resolveFileURI(uri: string): ResolvedFileURI {
```
Comment (felixfbecker) [inline src/uri.ts]: Perhaps name it `resolveDocumentURI` to not give the impression this takes a `file:` URI

File: src/uri.ts [hunk 3]
```diff
@@ -2,17 +2,22 @@ import { CodecovGetCommitCoverageArgs } from './api'
...
+export interface ResolvedFileURI extends ResolvedURI {
     path: string
 }
 
 /**
- * Resolve a URI of the forms git://github.com/owner/repo?rev#path and file:///path to an absolute reference, using
- * the given base (root) URI.
+ * Resolve a URI of the forms git://github.com/owner/repo?rev, using the given base (root) URI.
  */
 export function resolveURI(uri: string): ResolvedURI {
```
Comment (felixfbecker) [inline src/uri.ts]: Suggest to rename to `resolveRootURI`

File: src/uri.ts [hunk 4]
```diff
@@ -2,17 +2,22 @@ import { CodecovGetCommitCoverageArgs } from './api'
 import { Endpoint, Settings } from './settings'
 
 /**
- * A resolved URI identifies a path in a repository at a specific revision.
+ * A resolved URI without an identified path.
  */
 export interface ResolvedURI {
```
Comment (felixfbecker) [inline src/uri.ts]: `ResolvedRootURI`

File: src/uri.ts [hunk 5]
```diff
@@ -2,17 +2,22 @@ import { CodecovGetCommitCoverageArgs } from './api'
...
     repo: string
     rev: string
+}
+
+/**
+ * A resolved URI with an identified path in a repository at a specific revision.
+ */
+export interface ResolvedFileURI extends ResolvedURI {
```
Comment (felixfbecker) [inline src/uri.ts]: `ResolvedDocumentURI`
